### PR TITLE
OAuth implemented

### PR DESCRIPTION
**Pull request by jadrio**
Omniauth has been implemented and working with Facebook and Twitter. However, this implementation is unable to link the Twitter account to an existing account.
I created a Facebook and Twitter application to get this to work, but I have not included the figaro config file since these are supposed to be secret.

Adding other OAuth providers should be as simple as adding their gem, and initializing them in devise.rb
There is a omniauth-meetup gem.

### CODE REVIEW

**Comment by jamesdabbs** [comment]
Remind me what the deal was with the email verification: were some providers not returning an email? Or was it just that that email might not be verified?

**Comment by jadrio** [comment]
Some providers are not returning the email so we ask the user for their
email post oauth. If the user had already created an account with that
email they will get an error saying the email is already taken. This means
we are unable to link the accounts to a single entity so an user will have
multiple accounts.
I spent a little bit of time today adding bootstrap to the app. You can
take a look at it if you want on my fork, branch bootstrapin.

Let me know if you want me to do anything.

Thanks,

Jose Diaz

**Comment by jamesdabbs** [comment]
Ah, that'd be great. I did a little work on the layout / navbar yesterday,
but my internet was down when I went to push, so I just pushed that up now.
You may want to rebase whatever you've got so far from there.

One thought: it'd be nice for the vote stuff to be an [ interested | not
interested ] button group (with nothing selected by default).

**Comment by jadrio** [comment]
I'll get on it after work.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Pull request merged**
